// ********RoostGPT********
// Test generated by RoostGPT for test csharp-coding-examples using AI Type Open AI and AI Model gpt-4-1106-preview



// ********RoostGPT********
using System;
using System.Net.Http;
using NUnit.Framework;

namespace SwissTransport.Core.Test
{
    [TestFixture]
    public class Dispose_b753ff24a4
    {
        private Transport _transport;

        [SetUp]
        public void SetUp()
        {
            // TODO: Replace the HttpClient with a mock if needed
            _transport = new Transport();
        }

        [Test]
        public void Dispose_ShouldDisposeHttpClient_WithoutExceptions()
        {
            Assert.DoesNotThrow(() => _transport.Dispose());
        }

        [Test]
        public void Dispose_CalledMultipleTimes_ShouldNotThrowException()
        {
            Assert.DoesNotThrow(() => _transport.Dispose());
            Assert.DoesNotThrow(() => _transport.Dispose());
        }

        [TearDown]
        public void TearDown()
        {
            _transport.Dispose();
        }
    }
}

