// ********RoostGPT********
// Test generated by RoostGPT for test csharp-coding-examples using AI Type Open AI and AI Model gpt-4



// ********RoostGPT********
using System;
using NUnit.Framework;
using SwissTransport.Core;
using SwissTransport.Models;

namespace SwissTransport.Core.Test
{
    [TestFixture]
    public class GetStationBoard_7c8e85b58d
    {
        private Transport _transport;

        [SetUp]
        public void Setup()
        {
            _transport = new Transport();
        }

        [Test]
        public void GetStationBoard_ValidStationAndId_ReturnsStationBoardRoot()
        {
            // Arrange
            var station = "Zurich";
            var id = "8503000";

            // Act
            var result = _transport.GetStationBoard(station, id);

            // Assert
            Assert.IsNotNull(result);
            Assert.AreEqual(station, result.Station.Name);
        }

        [Test]
        public void GetStationBoard_InvalidStation_ThrowsArgumentNullException()
        {
            // Arrange
            var station = string.Empty; // TODO: Change this value
            var id = "8503000";

            // Act & Assert
            Assert.Throws<ArgumentNullException>(() => _transport.GetStationBoard(station, id));
        }

        [Test]
        public void GetStationBoard_InvalidId_ThrowsArgumentNullException()
        {
            // Arrange
            var station = "Zurich";
            var id = string.Empty; // TODO: Change this value

            // Act & Assert
            Assert.Throws<ArgumentNullException>(() => _transport.GetStationBoard(station, id));
        }

        [TearDown]
        public void TearDown()
        {
            _transport.Dispose();
        }
    }
}
