// ********RoostGPT********
// Test generated by RoostGPT for test csharp-coding-examples using AI Type Open AI and AI Model gpt-4



// ********RoostGPT********
using NUnit.Framework;
using SwissTransport.Core;
using SwissTransport.Models;
using System;
using System.Net.Http;
using System.Threading.Tasks;
using Newtonsoft.Json;

namespace SwissTransport.Core.Test
{
    [TestFixture]
    public class GetStations_7bfec3227d
    {
        private Transport _transport;

        [SetUp]
        public void SetUp()
        {
            _transport = new Transport();
        }

        [Test]
        public void GetStations_ValidQuery_ReturnsStations()
        {
            // Arrange
            string query = "Bern";

            // Act
            var result = _transport.GetStations(query);

            // Assert
            Assert.IsNotNull(result);
            Assert.IsTrue(result.StationList.Count > 0);
            Assert.IsTrue(result.StationList[0].Name.Contains(query));
        }

        [Test]
        public void GetStations_EmptyQuery_ThrowsArgumentNullException()
        {
            // Arrange
            string query = string.Empty;

            // Act & Assert
            Assert.Throws<ArgumentNullException>(() => _transport.GetStations(query));
        }

        [TearDown]
        public void TearDown()
        {
            _transport.Dispose();
        }
    }
}
